project:
  name: data-warehouse-proj
  environment: development

master_data:
  customers: 1000
  products: 200
  suppliers: 20
  warehouses: 4
  categories: 15

producer:
  events_per_second: 20

aws:
  region: ap-southeast-2
  bucket: abhinav-ecommerce-data-lake

kafka:
  bootstrap_servers: localhost:9092

snowflake:
  warehouse: COMPUTE_WH
  database: ECOMMERCE_DW
  schema_name: RAW