"""
Session Simulation Rules.
"""

PRODUCT_VIEWS_MIN = 1
PRODUCT_VIEWS_MAX = 5

ADD_TO_CART_PROBABILITY = 0.40

CHECKOUT_PROBABILITY = 0.80

PAYMENT_SUCCESS_PROBABILITY = 0.95

RETURN_PROBABILITY = 0.02